[project]
name = "jack-compiler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kyoya Iwatsuru", email = "kyoyaiwatsuru@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
JackCompiler = "jack_compiler:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff==0.12.8",
]

[tool.ruff]
# Set the maximum line length to 79.
line-length = 79

[tool.ruff.lint]
# Add the `line-too-long` rule to the enforced rule set.
extend-select = ["E501"]
